### ISSUE TITLE
关于7.1版本的问题

### ISSUE THREAD

**Issue by Oeeder** [cssxsh/pixiv-helper#15]
新版本安装好之后出现了两个问题。
一个是发送色图指令之后会有错误
后台显示错误如下：
2021-07-07 17:06:04 W/pixiv-helper: java.lang.StackOverflowError
java.lang.StackOverflowError
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:88)
        at jdk.proxy5/jdk.proxy5.$Proxy25.eroRandom(Unknown Source)
        at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$getEroArtWorkInfos$2$1.invoke(PixivEroCommand.kt:37)
        at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$getEroArtWorkInfos$2$1.invoke(PixivEroCommand.kt:37)
        at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:104)
        at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:97)
        at xyz.cssxsh.mirai.plugin.PixivHelperPlugin.useSession$helper(PixivHelperPlugin.kt:28)
        at xyz.cssxsh.mirai.plugin.PixivUtilsKt.useMappers(PixivUtils.kt:97)
        at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.getEroArtWorkInfos(PixivEroCommand.kt:37)
        at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.getEroArtWorkInfos(PixivEroCommand.kt:40)

“  at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.getEroArtWorkInfos(PixivEroCommand.kt:40)”这个有很多行的错误，就不打上去了。
以及使用tag指令时，会出现：
读取色图失败，

**Comment by cssxsh** [comment]
涩图间隔设置大小是多少？

**Comment by cssxsh** [comment]
涩图间隔设置大小是多少？

**Comment by Oeeder** [comment]
默认的，没设置过。

本来以为是我之前旧版本配置残留的问题。
我这边尝试过把缓存文件，配置文件全部删除掉。

尝试后也是这样的结果

**Comment by cssxsh** [comment]
> 默认的，没设置过。
> 
> 本来以为是我之前旧版本配置残留的问题。
> 我这边尝试过把缓存文件，配置文件全部删除掉。
> 
> 尝试后也是这样的结果

ero 指令可能是因为缓存近乎为空的原因

**Comment by Oeeder** [comment]
我这边尝试重新缓存一下图片。
那TAG的问题呢。

**Comment by cssxsh** [comment]
> 我这边尝试重新缓存一下图片。
> 那TAG的问题呢。

添加新参数时代码测试不完全，待会发布新版本修复

**Comment by cssxsh** [comment]
https://github.com/cssxsh/pixiv-helper/releases/tag/v0.7.2
