### ISSUE TITLE
MiraiAndroid 中 无法加载 Mybatis Mapper

### ISSUE THREAD

**Issue by Sanze2000** [cssxsh/pixiv-helper#21]
使用的是MiraiAndroid 3.2.1，用了编译并安装选项并勾选了脱糖选项
控制台输出如下
```
<font color="#DD1C1A">[ERROR]</font><![CDATA[org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): xyz.cssxsh.mirai.plugin.dao.ArtWorkInfoMapper.count]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:53)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.lambda$cachedInvoker$0$MapperProxy(MapperProxy.java:115)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.-$$Lambda$MapperProxy$T5NSXZXOQZhFD1r-0a3flqx709Y.apply(Unknown Source:6)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.cachedInvoker(MapperProxy.java:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at $Proxy20.count(Unknown Source)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivConfigKt$init$7$count$1.invoke(PixivConfig.kt:154)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivConfigKt$init$7$count$1.invoke(PixivConfig.kt:154)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:109)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivHelperPlugin.useSession$helper(PixivHelperPlugin.kt:28)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.useMappers(PixivUtils.kt:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivConfigKt$init$7.invokeSuspend(PixivConfig.kt:154)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[Exception in coroutine Plugin pixiv-helper of pixiv-helper]]>
<font color="#28BB28">[INFO]</font><![CDATA[自动登录....]]>
<font color="#FEAC48">[WARNING]</font><![CDATA[使用/backup auth 指令进行认证 ]]>
<font color="#FEAC48">[WARNING]</font><![CDATA[百度网盘初始化失败, java.lang.IllegalArgumentException: Required value was null.]]>
<font color="#28BB28">[INFO]</font><![CDATA[[AccountSecretsManager] Loaded account secrets from local cache.]]>
<font color="#28BB28">[INFO]</font><![CDATA[[AccountSecretsManager] Saved account secrets to local cache for fast login.]]>
<font color="#28BB28">[INFO]</font><![CDATA[Login successful.]]>
<font color="#28BB28">[INFO]</font><![CDATA[Bot login successful.]]>
<font color="#28BB28">[INFO]</font><![CDATA[PixivHelper:Friend(.....)#CacheTask start]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): xyz.cssxsh.mirai.plugin.dao.ArtWorkInfoMapper.eroRandom]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:53)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.lambda$cachedInvoker$0$MapperProxy(MapperProxy.java:115)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.-$$Lambda$MapperProxy$T5NSXZXOQZhFD1r-0a3flqx709Y.apply(Unknown Source:6)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.cachedInvoker(MapperProxy.java:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at $Proxy20.eroRandom(Unknown Source)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$getEroArtWorkInfos$1.invoke(PixivEroCommand.kt:39)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$getEroArtWorkInfos$1.invoke(PixivEroCommand.kt:39)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:109)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivHelperPlugin.useSession$helper(PixivHelperPlugin.kt:28)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.useMappers(PixivUtils.kt:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.getEroArtWorkInfos(PixivEroCommand.kt:39)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.access$getEroArtWorkInfos(PixivEroCommand.kt:12)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$ero$2.invokeSuspend(PixivEroCommand.kt:70)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$ero$2.invoke(Unknown Source:8)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$ero$2.invoke(Unknown Source:4)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$sendIllust$6.invokeSuspend(PixivUtils.kt:81)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$sendIllust$6.invoke(Unknown Source:8)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$sendIllust$6.invoke(Unknown Source:4)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.sendIllust(PixivUtils.kt:56)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.sendIllust(PixivUtils.kt:80)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.ero(PixivEroCommand.kt:60)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.lang.reflect.Method.invoke(Native Method)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:294)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(Unknown Source:19)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(Unknown Source:6)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(Unknown Source:0)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:130)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(Unknown Source:2)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[]]>
<font color="#28BB28">[INFO]</font><![CDATA[PixivHelper:Group(.....)#CacheTask start]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): xyz.cssxsh.mirai.plugin.dao.ArtWorkInfoMapper.eroRandom]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:53)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.lambda$cachedInvoker$0$MapperProxy(MapperProxy.java:115)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.-$$Lambda$MapperProxy$T5NSXZXOQZhFD1r-0a3flqx709Y.apply(Unknown Source:6)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.cachedInvoker(MapperProxy.java:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at $Proxy20.eroRandom(Unknown Source)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$getEroArtWorkInfos$1.invoke(PixivEroCommand.kt:39)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$getEroArtWorkInfos$1.invoke(PixivEroCommand.kt:39)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:109)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$useMappers$1.invoke(PixivUtils.kt:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivHelperPlugin.useSession$helper(PixivHelperPlugin.kt:28)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.useMappers(PixivUtils.kt:102)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.getEroArtWorkInfos(PixivEroCommand.kt:39)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.access$getEroArtWorkInfos(PixivEroCommand.kt:12)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$ero$2.invokeSuspend(PixivEroCommand.kt:70)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$ero$2.invoke(Unknown Source:8)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand$ero$2.invoke(Unknown Source:4)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$sendIllust$6.invokeSuspend(PixivUtils.kt:81)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$sendIllust$6.invoke(Unknown Source:8)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt$sendIllust$6.invoke(Unknown Source:4)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.sendIllust(PixivUtils.kt:56)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.PixivUtilsKt.sendIllust(PixivUtils.kt:80)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at xyz.cssxsh.mirai.plugin.command.PixivEroCommand.ero(PixivEroCommand.kt:60)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at java.lang.reflect.Method.invoke(Native Method)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:294)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(Unknown Source:19)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(Unknown Source:6)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(Unknown Source:0)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:130)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(Unknown Source:2)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)]]>
<font color="#DD1C1A">[ERROR]</font><![CDATA[]]>`
同时聊天消息报错
`读取色图失败， Invalid bound statement (not found): xyz.cssxsh.mirai.plugin.dao.ArtWorkInfoMapper.eroRandom
```
另外登录（使用过新浪微博登录和token刷新），搜索画师名字是没有问题的

**Comment by cssxsh** [comment]
首先是目前是不建议在 `MiraiAndroid` 运行的，因为插件缓存很大，`MiraiAndroid` 不好清理。 所以没考虑过适配 `MiraiAndroid`

**Comment by cssxsh** [comment]
看报错像是 没读取成功资源文件

**Comment by cssxsh** [comment]
这算是 MiraiAndroid 的问题
