### ISSUE TITLE
使用/pixiv cookie登录时显示消息回复失败

### ISSUE THREAD

**Issue by manirover** [cssxsh/pixiv-helper#56]
CPU: 
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
```

OS：`Ubuntu 20.04.3 LTS`

各组件版本：
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)

"net.mamoe:mirai-console" v2.7.1-dev-1
"net.mamoe:mirai-console-terminal" v2.7.1-dev-1
"net.mamoe:mirai-core-all" v2.7.1-dev-1
"org.itxtech:mcl-addon" v1.2.2
"net.mamoe:chat-command" v0.5.1
pixiv-helper v1.5.1
```

问题复现：
安装好插件，浏览器注销pixiv，清除浏览器cookie，重新登录，导出cookie放置到工作目录，在私聊环境执行`/pixiv cookie`，提示消息回复失败。再尝试`/cache`的时候，会显示AuthException，所以应该是没有登录成功。控制台内建指令和[B站插件](https://github.com/cssxsh/bilibili-helper)的指令都能正常使用，所以应该不是mirai的问题。

控制台日志：
```
2021-09-19 02:45:29 V/Bot.***: ***(***) -> /pixiv cookie
2021-09-19 02:45:29 V/Bot.***: Event: FriendMessagePreSendEvent(target=Friend(***), message=加载 cookie 从 .../mcl/cookie.json)
2021-09-19 02:45:30 V/Bot.***: Friend(***) <- 加载 cookie 从 .../mcl/cookie.json
2021-09-19 02:45:30 V/Bot.***: Event: FriendMessagePostSendEvent(target=Friend(***), message=加载 cookie 从 .../mcl/cookie.json, exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@19ac722f)
2021-09-19 02:45:33 W/pixiv-helper: 消息回复失败
java.lang.IllegalStateException: https://accounts.pixiv.net/login?return_to=%2Faccount-selected To https://accounts.pixiv.net/login?return_to=%2Faccount-selected
        at xyz.cssxsh.pixiv.OtherAuthKt.redirect(OtherAuth.kt:44)
        at xyz.cssxsh.pixiv.OtherAuthKt.access$redirect(OtherAuth.kt:1)
        at xyz.cssxsh.pixiv.OtherAuthKt$redirect$1.invokeSuspend(OtherAuth.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-09-19 02:45:34 V/Bot.***: Event: FriendMessagePreSendEvent(target=Friend(***), message=[mirai:quote:[15164],[1561273249]]java.lang.IllegalStateException: https://accounts.pixiv.net/login?return_to=%2Faccount-selected To https://accounts.pixiv.net/login?return_to=%2Faccount-selected)
2021-09-19 02:45:34 V/Bot.***: Friend(***) <- [mirai:quote:[15164],[1561273249]]java.lang.IllegalStateException: https://accounts.pixiv.net/login?return_to=%2Faccount-selected To https://accounts.pixiv.net/login?return_to=%2Faccount-selected
2021-09-19 02:45:34 V/Bot.***: Event: FriendMessagePostSendEvent(target=Friend(***), message=[mirai:quote:[15164],[1561273249]]java.lang.IllegalStateException: https://accounts.pixiv.net/login?return_to=%2Faccount-selected To https://accounts.pixiv.net/login?return_to=%2Faccount-selected, exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@5c0728bf)
```

网络日志：
```
[0m2021-09-19 02:45:29 V/Net ***: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-19 02:45:30 V/Net ***: Recv: MessageSvc.PbSendMsg[0m
[0m2021-09-19 02:45:34 V/Net ***: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-19 02:45:34 V/Net ***: Recv: MessageSvc.PbSendMsg[0m
[0m2021-09-19 02:46:21 V/Net ***: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-19 02:46:21 V/Net ***: Recv: MessageSvc.PbSendMsg[0m
```

**Comment by manirover** [comment]
问题出在cookies，可能是因为没有成功刷进登录状态。我重新导出了一次cookies就能用了。
