### ISSUE TITLE
找不到联系人

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/pixiv-helper#64]
```
2021-12-25 14:59:15 E/pixiv-helper: Exception in coroutine PixivHelperScheduler of pixiv-helper
java.lang.IllegalArgumentException: 找不到联系人 -1074197861
        at xyz.cssxsh.mirai.plugin.PixivTaskKt.getHelper(PixivTask.kt:35)
        at xyz.cssxsh.mirai.plugin.PixivTaskKt.run(PixivTask.kt:256)
        at xyz.cssxsh.mirai.plugin.PixivHelperScheduler$runTimerTask$1.invokeSuspend(PixivHelperScheduler.kt:22)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by cssxsh** [comment]
请检查机器人是否有群联系人 `1074197861`

**Comment by LaoLittle** [comment]
> 请检查机器人是否有群联系人 `1074197861`

我解散了那个群，然后删除了Task配置，应该没问题了
