### ISSUE TITLE
java.lang.ClassCastException: class io.ktor.client.call.TypeInfo

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/pixiv-helper#66]
```
2022-01-15 14:18:50 E/pixiv-helper: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.pixiv-helper of pixiv-helper
java.lang.ClassCastException: class io.ktor.client.call.TypeInfo cannot be cast to class io.ktor.util.reflect.TypeInfo (io.ktor.client.call.TypeInfo is in unnamed module of loader 'app'; io.ktor.util.reflect.TypeInfo is in unnamed module of loader net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader @51d9b06c)
        at io.ktor.client.features.json.JsonSerializer$DefaultImpls.read(JsonSerializer.kt:31)
        at io.ktor.client.features.json.serializer.KotlinxSerializer.read(KotlinxSerializer.kt:20)
        at io.ktor.client.features.json.JsonFeature$Feature$install$2.invokeSuspend(JsonFeature.kt:161)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Linux无问题

**Comment by cssxsh** [comment]
版本信息？
插件版本
mirai版本
java版本

**Comment by LaoLittle** [comment]
我是直接从linux服务器上复制过来的
mirai 2.9.2
linux jdk17 windows jdk17
pixiv-helper1.7.3

**Comment by cssxsh** [comment]
你确定 mirai 版本是 `2.9.2` ？

**Comment by LaoLittle** [comment]
> 你确定 mirai 版本是 `2.9.2` ？

`2.9.1`（打错了，用的依赖都是2.9.2，习惯）

**Comment by LaoLittle** [comment]
不知道是不是和漂流瓶插件依赖冲突了

漂流瓶插件的依赖
```
dependencies {
    implementation("io.ktor:ktor-client-serialization:1.5.4")
}
```

**Comment by cssxsh** [comment]
你有安装其他插件吗

**Comment by LaoLittle** [comment]
> 你有安装其他插件吗

漂流瓶的话ktor版本和`pixiv-helper`版本都是`1.5.4`（不过不知道`1.7.3` -> `1.8.2`有没有更新ktor？）
其他的貌似都是使用mirai的ktor

**Comment by cssxsh** [comment]
> > 你有安装其他插件吗
> 
> 漂流瓶的话ktor版本和`pixiv-helper`版本都是`1.5.4`（不过不知道`1.7.3` -> `1.8.2`有没有更新ktor？） 其他的貌似都是使用mirai的ktor

给我详细的列表比较好

**Comment by LaoLittle** [comment]
- [SimpleGroupAuth-1.0](https://mirai.mamoe.net/topic/475)
- [bing-daily-0.1.0](https://mirai.mamoe.net/topic/706)
- [CaiyunAI-1.0.5](https://mirai.mamoe.net/topic/816)
- chat-command-0.5.1
- debug-helper-1.1.7.mirai
- [genshin-sign-0.3.3](https://mirai.mamoe.net/topic/692)
- [drift-bottle-1.4.0](https://mirai.mamoe.net/topic/841)
- [Molly-1.1.0](https://mirai.mamoe.net/topic/809)
- [OsuMapSuggester-2.1](https://mirai.mamoe.net/topic/787)
- pixiv-helper-1.7.3
- [SCTimetableBot-0.4.7](https://github.com/StageGuard/SuperCourseTimetableBot)

------
还有一些自用的
![image](https://user-images.githubusercontent.com/93422095/149694274-5a99e383-054d-4d79-bf37-f730f740698e.png)
这三个没依赖
![image](https://user-images.githubusercontent.com/93422095/149694348-a7133579-06d9-4dac-975a-cded14fe09e3.png)
这个是https://github.com/LaoLittle/WordCloud

**Comment by LaoLittle** [comment]
这应该不是本插件的问题（大概
