### ISSUE TITLE
再一次进行初次安装后没法生成config文件

### ISSUE THREAD

**Issue by Oeeder** [cssxsh/pixiv-helper#77]
因为一些原因，之前旧版的config和data都被我删除了
之后再想安装最新的，但是报错，好像无法生成config？
```
2022-03-09 16:30:01 E/pixiv-helper: java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/plugin/PixivConfigKt
java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/plugin/PixivConfigKt
        at pixiv-helper-1.9.4.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperSettings.<clinit>(PixivHelperSettings.kt:50)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
        at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1126)
        at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1107)
        at java.base/java.lang.reflect.Field.get(Field.java:419)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
        at pixiv-helper-1.9.4.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion$configs$2.invoke(PixivHelperConfig.kt:9)
        at pixiv-helper-1.9.4.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion$configs$2.invoke(PixivHelperConfig.kt:8)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at pixiv-helper-1.9.4.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion.getConfigs(PixivHelperConfig.kt:8)
        at pixiv-helper-1.9.4.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion.iterator(PixivHelperConfig.kt:20)
        at pixiv-helper-1.9.4.mirai.jar//xyz.cssxsh.mirai.plugin.PixivHelperPlugin.onEnable(PixivHelperPlugin.kt:31)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:258)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:224)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: xyz.cssxsh.mirai.plugin.PixivConfigKt
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.resolvePluginPublicClass$mirai_console(JvmPluginClassLoader.kt:209)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.resolvePluginSharedLibAndPluginClass$mirai_console(JvmPluginClassLoader.kt:200)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:231)
        ... 59 more
```

**Comment by cssxsh** [comment]
最新版mirai有问题，请回退版本
