### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by soundofautumn** [cssxsh/pixiv-helper#80]
[92m2022-04-25 09:23:16 I/main: Starting mirai-console...[0m[m
[92m2022-04-25 09:23:16 I/main: Backend: version 2.11.0-M1, built on 2022-03-08 20:34:54.[0m[m
[92m2022-04-25 09:23:16 I/main: Frontend Terminal: version 2.11.0-M1, provided by Mamoe Technologies[0m[m
[92m2022-04-25 09:23:16 I/main: Welcome to visit https://mirai.mamoe.net/[0m[m
[91m2022-04-25 09:23:17 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".[0m[m
[91m2022-04-25 09:23:17 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation[0m[m
[91m2022-04-25 09:23:17 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.[0m[m
[91m2022-04-25 09:23:17 W/JvmPlugin[pixiv-helper-1.9.5.mirai.jar]: Linked class xyz.cssxsh.mirai.plugin.MiraiHibernate in mirai-hibernate-plugin-2.0.7.jar but plugin not depend on it.[0m[m
[91m2022-04-25 09:23:17 W/JvmPlugin[pixiv-helper-1.9.5.mirai.jar]: Class loading logic may change in feature.[0m[m
[92m2022-04-25 09:23:17 I/plugin: Successfully loaded plugin PatPat v2.0.1[0m[m
[92m2022-04-25 09:23:17 I/plugin: Successfully loaded plugin Chat Command v0.5.0[0m[m
[92m2022-04-25 09:23:17 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.4.0[0m[m
[92m2022-04-25 09:23:17 I/plugin: Successfully loaded plugin MCL Addon v1.2.2[0m[m
[91m2022-04-25 09:23:17 W/mirai-hibernate-plugin: 未安装 mirai-slf4j-bridge.[0m[m
[92m2022-04-25 09:23:17 I/plugin: Successfully loaded plugin mirai-hibernate-plugin v2.0.7[0m[m
[92m2022-04-25 09:23:17 I/plugin: Successfully loaded plugin pixiv-helper v1.9.5[0m[m
[92m2022-04-25 09:23:17 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop[0m[m
[92m2022-04-25 09:23:17 I/PatPat: 检测到当前为Linux系统，将使用headless模式[0m[m
[92m2022-04-25 09:23:17 I/PatPat: 缓存已自动清理[0m[m
[92m2022-04-25 09:23:17 I/PatPat: 摸头插件已加载[0m[m
[91m2022-04-25 09:23:17 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key[0m[m
[92m2022-04-25 09:23:17 I/Mirai HTTP API: ********************************************************[0m[m
[92m2022-04-25 09:23:17 I/http adapter: >>> [http adapter] is listening at http://localhost:8080[0m[m
[92m2022-04-25 09:23:17 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYPPSVUfvv[0m[m
[92m2022-04-25 09:23:17 I/Mirai HTTP API: adaptors: [http][0m[m
[92m2022-04-25 09:23:17 I/Mirai HTTP API: ********************************************************[0m[m
[92m2022-04-25 09:23:17 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb[0m[m
[91m2022-04-25 09:23:17 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...[0m[m
[91m2022-04-25 09:23:18 W/mirai-hibernate-plugin: Linked class com.typesafe.config.Config in mirai-api-http-2.4.0.jar but plugin not depend on it.[0m[m
[91m2022-04-25 09:23:18 W/mirai-hibernate-plugin: Class loading logic may change in feature.[0m[m
[91m2022-04-25 09:23:18 W/stderr: MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.[0m[m
[92m2022-04-25 09:23:19 I/mirai-hibernate-plugin: Database jdbc:sqlite:file:///root/mirai/mcl/data/xyz.cssxsh.mirai.plugin.mirai-hibernate-plugin/hibernate.sqlite by SQLite JDBC.[0m[m
[31m2022-04-25 09:23:19 E/pixiv-helper: java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/plugin/PixivConfigKt
java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/plugin/PixivConfigKt
	at pixiv-helper-1.9.5.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperSettings.<clinit>(PixivHelperSettings.kt:50)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
	at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
	at pixiv-helper-1.9.5.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion$configs$2.invoke(PixivHelperConfig.kt:9)
	at pixiv-helper-1.9.5.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion$configs$2.invoke(PixivHelperConfig.kt:8)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at pixiv-helper-1.9.5.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion.getConfigs(PixivHelperConfig.kt:8)
	at pixiv-helper-1.9.5.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion.iterator(PixivHelperConfig.kt:20)
	at pixiv-helper-1.9.5.mirai.jar//xyz.cssxsh.mirai.plugin.PixivHelperPlugin.onEnable(PixivHelperPlugin.kt:31)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:258)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:224)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
	at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
	at org.itxtech.mcl.Loader.start(Loader.java:176)
	at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ClassNotFoundException: xyz.cssxsh.mirai.plugin.PixivConfigKt
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.resolvePluginPublicClass$mirai_console(JvmPluginClassLoader.kt:209)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.resolvePluginSharedLibAndPluginClass$mirai_console(JvmPluginClassLoader.kt:200)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:231)
	... 61 more
[0m[m
[92m2022-04-25 09:23:19 I/main: 6 plugin(s) enabled.[0m[m

**Comment by soundofautumn** [comment]
哦是因为没更新，这个问题解决了
