### ISSUE TITLE
升级后出错

### ISSUE THREAD

**Issue by zjm54321** [cssxsh/pixiv-helper#81]
安装了1.9.5版出错，后回退1.9.0也出错了。（把依赖的也一起升级了）
```
2022-05-01 13:11:34 E/pixiv-helper: java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/plugin/PixivConfigKt
                                                                                           Fjava.lang.NoClassDefFoundError: xyz/cssxsh/mirai/plugin/PixivConfigKt
                                                                  z     at pixiv-helper-1.9.0-RC.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperSettings.<clinit>(PixivHelperSettings.kt:50)
  N     at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
                                                                                    P   at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
                                                                       s        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
   b    at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
         L      at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1126)
                                                                                          H   at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1107)
                                                                     :  at java.base/java.lang.reflect.Field.get(Field.java:419)
                                 [      at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117)
                                  \     at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
                                   Z    at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
                                 U      at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
                            P   at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
                at pixiv-helper-1.9.0-RC.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion$configs$2.invoke(PixivHelperConfig.kt:9)
                                                        at pixiv-helper-1.9.0-RC.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion$configs$2.invoke(PixivHelperConfig.kt:8)
                                                                                              at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                        at pixiv-helper-1.9.0-RC.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion.getConfigs(PixivHelperConfig.kt:8)
                                                                                              at pixiv-helper-1.9.0-RC.mirai.jar//xyz.cssxsh.mirai.plugin.data.PixivHelperConfig$Companion.iterator(PixivHelperConfig.kt:20)
                              q at pixiv-helper-1.9.0-RC.mirai.jar//xyz.cssxsh.mirai.plugin.PixivHelperPlugin.onEnable(PixivHelperPlugin.kt:33)
                                                w       at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
                                                                              q at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:258)
 p      at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
                       Z        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
                         ]      at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
                            T   at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
                   }    at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
                                                        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:224)
                                                                                            j at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
        q       at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
                                y       at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
                                                                g       at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
                                                                              S at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                  e     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
                                                                            m   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                            ? at java.base/java.lang.reflect.Method.invoke(Method.java:567)
                                                            7   at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
                      S at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
          e     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
                    m   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                    ?   at java.base/java.lang.reflect.Method.invoke(Method.java:567)
      @ at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
                                                                      L at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
                                                   L    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
                                   H    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
               R        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
         M      at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
                                                                                           L  at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
                                                                         R      at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
                                                                 E      at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
                                            R   at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
                                 W      at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
                              : at org.mozilla.javascript.Context.call(Context.java:554)
                                                                                        H     at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
                                                                     N  at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
                                                     R  at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
                                         6      at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
     K  at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
                                                                                 2      at org.itxtech.mcl.Loader.start(Loader.java:129)
                                         0      at org.itxtech.mcl.Loader.main(Loader.java:53)
                                                                                              SCaused by: java.lang.ClassNotFoundException: xyz.cssxsh.mirai.plugin.PixivConfigKt
                                                                                  I     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
                                                                        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.resolvePluginPublicClass$mirai_console(JvmPluginClassLoader.kt:209)
                at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.resolvePluginSharedLibAndPluginClass$mirai_console(JvmPluginClassLoader.kt:200)
                                                                 i      at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:231)
        ... 59 more
```

**Comment by cssxsh** [comment]
`mirai-console` 2.11 版本特性还不稳定，请回退 `mirai-console` 版本
