### ISSUE TITLE
无法使用微博登入

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/pixiv-helper#92]
```
2022-07-09 10:12:22 W/pixiv-helper: Exception in executing command `[mirai:source:ids=[], internalIds=[], from group to at]/pixiv sina`
java.lang.IllegalArgumentException: 跳转到 pixiv://... 失败
        at pixiv-helper-2.0.0-M2.mirai2.jar[private]//xyz.cssxsh.pixiv.OtherAuthKt.redirect(OtherAuth.kt:74)
        at pixiv-helper-2.0.0-M2.mirai2.jar[private]//xyz.cssxsh.pixiv.OtherAuthKt.access$redirect(OtherAuth.kt:1)
        at pixiv-helper-2.0.0-M2.mirai2.jar[private]//xyz.cssxsh.pixiv.OtherAuthKt$redirect$1.invokeSuspend(OtherAuth.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
pixiv 服务器抽风
最后一步跳转失败

**Comment by LaoLittle** [comment]
了解
